# Enable logging
logger:
  baud_rate: 0
  level: INFO  
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: ""
  reboot_timeout: 1h

ota:
  password: ""

web_server:
  port: 80
  ota: false
  local: true
  include_internal: true
