esphome:
  name: pdu-${devicename}
  friendly_name: PDU ${display_devicename}
      
esp32:
  board: esp32dev

uart:
  rx_pin:
    number: 15
  tx_pin:
    number: 17
  baud_rate: 9600
  stop_bits: 1

modbus:

binary_sensor:
  - platform: status
    name: "${display_devicename} Status"

sensor:
  - platform: pzemac
    id: pzemac1
    energy:
      name: "energy_ac1"
      id: "energy_ac1"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac1"
      id: "current_ac1"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac1"
      id: "voltage_ac1"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac1"
      id: "frequency_ac1"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac1"
      id: "factor_ac1"
      accuracy_decimals: 1
    power:
      name: "power_ac1"
      id: "power_ac1"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 1

  - platform: pzemac
    id: pzemac2
    energy:
      name: "energy_ac2"
      id: "energy_ac2"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac2"
      id: "current_ac2"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac2"
      id: "voltage_ac2"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac2"
      id: "frequency_ac2"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac2"
      id: "factor_ac2"
      accuracy_decimals: 1
    power:
      name: "power_ac2"
      id: "power_ac2"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 2

  - platform: pzemac
    id: pzemac3
    energy:
      name: "energy_ac3"
      id: "energy_ac3"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac3"
      id: "current_ac3"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac3"
      id: "voltage_ac3"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac3"
      id: "frequency_ac3"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac3"
      id: "factor_ac3"
      accuracy_decimals: 1
    power:
      name: "power_ac3"
      id: "power_ac3"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 3

  - platform: pzemac
    id: pzemac4
    energy:
      name: "energy_ac4"
      id: "energy_ac4"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac4"
      id: "current_ac4"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac4"
      id: "voltage_ac4"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac4"
      id: "frequency_ac4"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac4"
      id: "factor_ac4"
      accuracy_decimals: 1
    power:
      name: "power_ac4"
      id: "power_ac4"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 4

  - platform: pzemac
    id: pzemac5
    energy:
      name: "energy_ac5"
      id: "energy_ac5"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac5"
      id: "current_ac5"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac5"
      id: "voltage_ac5"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac5"
      id: "frequency_ac5"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac5"
      id: "factor_ac5"
      accuracy_decimals: 1
    power:
      name: "power_ac5"
      id: "power_ac5"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 5

  - platform: pzemac
    id: pzemac6
    energy:
      name: "energy_ac6"
      id: "energy_ac6"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac6"
      id: "current_ac6"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac6"
      id: "voltage_ac6"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac6"
      id: "frequency_ac6"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac6"
      id: "factor_ac6"
      accuracy_decimals: 1
    power:
      name: "power_ac6"
      id: "power_ac6"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 6

  - platform: pzemac
    id: pzemac7
    energy:
      name: "energy_ac7"
      id: "energy_ac7"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac7"
      id: "current_ac7"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac7"
      id: "voltage_ac7"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac7"
      id: "frequency_ac7"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac7"
      id: "factor_ac7"
      accuracy_decimals: 1
    power:
      name: "power_ac7"
      id: "power_ac7"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 6

  - platform: pzemac
    id: pzemac8
    energy:
      name: "energy_ac8"
      id: "energy_ac8"
      filters:
        - multiply: 0.002
      unit_of_measurement: kWh
      accuracy_decimals: 1
    current:
      name: "current_ac8"
      id: "current_ac8"
      accuracy_decimals: 1
    voltage:
      name: "voltage_ac8"
      id: "voltage_ac8"
      filters:
        - multiply: 1
      accuracy_decimals: 1
    frequency:
      name: "frequency_ac8"
      id: "frequency_ac8"
      accuracy_decimals: 1
    power_factor:
      name: "factor_ac8"
      id: "factor_ac8"
      accuracy_decimals: 1
    power:
      name: "power_ac8"
      id: "power_ac8"
      filters:
        - multiply: 1
      accuracy_decimals: 0
    update_interval: never
    address: 8

  - platform: total_daily_energy
    name: "energy_ac1_daily"
    power_id: power_ac1
    id: energy_ac1_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac2_daily"
    power_id: power_ac2
    id: energy_ac2_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac3_daily"
    power_id: power_ac3
    id: energy_ac3_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac4_daily"
    power_id: power_ac4
    id: energy_ac4_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac5_daily"
    power_id: power_ac5
    id: energy_ac5_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac6_daily"
    power_id: power_ac6
    id: energy_ac6_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac7_daily"
    power_id: power_ac7
    id: energy_ac7_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "energy_ac8_daily"
    power_id: power_ac8
    id: energy_ac8_daily
    unit_of_measurement: kWh
    accuracy_decimals: 1
    icon: mdi:counter
    filters:
      - multiply: 0.001

  - platform: template
    name: "total_power"
    id: "total_power"
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    accuracy_decimals: 1
    lambda: |-
      return id(power_ac1).state + id(power_ac2).state + id(power_ac3).state + id(power_ac4).state + id(power_ac5).state + id(power_ac6).state + id(power_ac7).state + id(power_ac8).state;

  - platform: template
    name: "energy_total_daily"
    id: "energy_total_daily"
    icon: mdi:counter
    device_class: energy
    state_class: measurement
    unit_of_measurement: kWh
    accuracy_decimals: 1
    lambda: |-
      return id(energy_ac1_daily).state + id(energy_ac2_daily).state + id(energy_ac3_daily).state + id(energy_ac4_daily).state + id(energy_ac5_daily).state + id(energy_ac6_daily).state + id(energy_ac7_daily).state + id(energy_ac8_daily).state ;


time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: restart
    name: "${display_devicename}_restart"

  - platform: uart
    name: "${display_devicename}_reset"
    data: [0x01, 0x42, 0x80, 0x11]

interval:
  - interval: 5s
    then:
      - delay: 150ms
      - lambda: "id(pzemac1).update();"
      - delay: 150ms
      - lambda: "id(pzemac2).update();"
      - delay: 150ms
      - lambda: "id(pzemac3).update();"
      - delay: 150ms
      - lambda: "id(pzemac4).update();"
      - delay: 150ms
      - lambda: "id(pzemac5).update();"
      - delay: 150ms
      - lambda: "id(pzemac6).update();"
      - delay: 150ms
      - lambda: "id(pzemac7).update();"
      - delay: 150ms
      - lambda: "id(pzemac8).update();"